### ISSUE TITLE
Parallel Execution / Multiple Drivers

### ISSUE THREAD

**Issue by tammomueller** [WaterfallEngineering/selenium-node-webdriver#1] opened 2013-03-05 03:57 UTC
Hi,

Great Job, this is by far the most usable library on the node js side.
One thing I wasn't able to find out is how to launch multiple drivers or flows.

The WebdriverJS lib has the concept of multiple flows but I wasn't able to find that concept.
I tried to create a new driver but it seems that it is reusing the existing session.

Any recommendations?

Thanks,

Tammo

**Comment by lawnsea** [comment] 2013-03-05 04:16
Thanks! Glad you found it helpful.

You'll have to dig into the Selenium code to find out why that is. `selenium-node-webdriver` tries to create a new WebDriver client for each call; see lines [62-65](https://github.com/WaterfallEngineering/selenium-node-webdriver/blob/master/lib/index.js#L62-L65).

**Comment by lawnsea** [comment] 2013-03-07 08:01
Closing this. Please re-open if you find that `selenium-node-webdriver` is the cause of your troubles.

**Closed as completed by lawnsea** 2013-03-07 08:01 UTC
